version: '3.8'
services:
  app:
    image: ${APP_IMAGE}
    build: .
    restart: always
    ports:
      - "${APP_LOCAL_PORT}:${APP_SERVER_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - .env